### ISSUE TITLE
Error processing image

### ISSUE THREAD

**Issue by 99991** [MangoLion/bgbye#1]
The Demo at https://fyrean.itch.io/bgbye-background-remover seems to be broken currently. I tried both Chrome and Firefox.

![cors](https://github.com/user-attachments/assets/efe5d6bb-bfa3-4b1d-9cfe-2359eee404ed)

![bad_gateway](https://github.com/user-attachments/assets/5ed97328-a2c5-4883-b006-1d26501b0d0c)

**Comment by MangoLion** [comment]
I found the issue, the server was up, but the port wasn't being forwarded through WSL. Resolved by setting WSL networking mode to mirroring.

**Comment by MangoLion** [comment]
The issue seems to be from restarting the server on WSL, the port completely stopped working for some reason. Rebooting WSL made the port open again.

**Comment by 99991** [comment]
Thank you for the quick fix! It works now.
